config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'auth/registrations',
    sessions: 'auth/sessions'
  }

  scope '(:locale)' do

    get '/conferences/new' => 'conferences#new', as: 'new_conference'
    post '/conferences' => 'conferences#create', as: 'create_conference'
    get '/conferences' => 'conferences#index', as: 'conference_index'
    delete '/conferences' => 'conferences#destroy'

    get '/conferences/past' => 'home#past', as: 'past_conferences'

    get '/conference_users' => 'conference_users#index', as: 'conference_users'
    get '/admin_users' => 'conference_users#admins', as: 'admin_users'
    delete '/conference_users' => 'conference_users#destroy'

    get '/profile' => 'crew_profiles#edit', as: 'edit_crew_profile'
    patch '/profile' => 'crew_profiles#update', as: 'update_crew_profile'

    get '/user/:person_id/edit' => 'users#edit', as: 'edit_crew_user'
    patch '/user/:person_id' => 'users#update', as: 'crew_user'
    post '/user/:person_id' => 'users#create'

    scope path: '/:conference_acronym' do
      namespace :public do
        get '/schedule' => 'schedule#index', as: 'schedule_index'
        get '/schedule/style' => 'schedule#style', as: 'schedule_style'
        get '/schedule/:day' => 'schedule#day', as: 'schedule'
        get '/events' => 'schedule#events', as: 'events'
        get '/timeline' => 'schedule#timeline', as: 'timeline'
        get '/booklet' => 'schedule#booklet', as: 'booklet'
        get '/events/:id' => 'schedule#event', as: 'event'
        get '/speakers' => 'schedule#speakers', as: 'speakers'
        get '/speakers/:id' => 'schedule#speaker', as: 'speaker'
        get '/qrcode' => 'schedule#qrcode', as: 'qrcode'
        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do
        resource :user, except: %i(new create)
        resource :person do
          member do
            get :export
            post :import
          end
          resource :availability
        end
        get '/events/:id/confirm/:token' => 'events#confirm', as: 'event_confirm_by_token'
        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end
        root to: 'welcome#show'
      end # namespace :cfp

      get '/recent_changes' => 'recent_changes#index', as: 'recent_changes'
      post '/schedule.pdf' => 'schedule#custom_pdf', as: 'schedule_custom_pdf', defaults: { format: :pdf }
      get '/schedule' => 'schedule#index', as: 'schedule'
      get '/schedule/update_track' => 'schedule#update_track', as: 'schedule_update_track'
      put '/schedule/update_event' => 'schedule#update_event', as: 'schedule_update_event'
      get '/schedule/new_pdf' => 'schedule#new_pdf', as: 'new_schedule_pdf'
      get '/schedule/html_exports' => 'schedule#html_exports'
      post '/schedule/create_static_export' => 'schedule#create_static_export'
      get '/schedule/download_static_export' => 'schedule#download_static_export'

      get '/statistics/events_by_state' => 'statistics#events_by_state', as: 'events_by_state_statistics'
      get '/statistics/language_breakdown' => 'statistics#language_breakdown', as: 'language_breakdown_statistics'
      get '/statistics/gender_breakdown' => 'statistics#gender_breakdown', as: 'gender_breakdown_statistics'

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
	get :edit_classifiers
        get :edit_ticket_server
        get :edit_notifications
        post :send_notification
      end
      get '/conferences/default_notifications' => 'conferences#default_notifications', as: 'conferences_default_notifications'

      resource :call_for_participation

      resources :people do
        resource :user
        resource :availability, except: %i(create show)
        resources :expenses
        resources :transport_needs
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
        member do
          put :attend
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
          get :export_accepted
          get :export_confirmed
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
          post :custom_notification
        end
        resource :event_rating
        resources :event_feedbacks
      end

      get '/reports' => 'reports#index', as: 'reports'
      get '/reports/on_people/:id' => 'reports#show_people', as: 'report_on_people'
      get '/reports/on_events/:id' => 'reports#show_events', as: 'report_on_events'
      get '/reports/on_statistics/:id' => 'reports#show_statistics', as: 'report_on_statistics'
      get '/reports/on_transport_needs/:id' => 'reports#show_transport_needs', as: 'report_on_transport_needs'

      post '/tickets/:id/person' => 'tickets#create_person', as: 'create_person_ticket'
      post '/tickets/:id/event' => 'tickets#create_event', as: 'create_event_ticket'

      resources :mail_templates do
        member do
          put :send_mail
        end
      end
    end # scope path: "/:conference_acronym"
    get '/:conference_acronym' => 'conferences#show', as: 'conference_crew'
  end # scope "(:locale)" do

  root to: 'home#index'
end

app/models/mail_template.rb
class MailTemplate < ApplicationRecord
  belongs_to :conference
  validates :name, presence: true
  validates :subject, presence: true
  validates :content, presence: true

  def content_for(user)
    content
      .gsub('#first_name',  user.first_name)
      .gsub('#last_name',   user.last_name)
      .gsub('#public_name', user.public_name)
  end

  def send_sync(filter)
    job = SendBulkMailJob.new
    job.perform self, filter
  end

  def send_async(filter)
    job = SendBulkMailJob.new
    job.async.perform self, filter
  end
end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < BaseConferenceController
  before_action :orga_only!

  def new
    @mail_template = MailTemplate.new
  end

  def edit
    @mail_template = @conference.mail_templates.find(params[:id])
  end

  def show
    @mail_template = @conference.mail_templates.find(params[:id])
    @send_filter_options = [
      ['All speakers involved in all confirmed events',   :all_speakers_in_confirmed_events],
      ['All speakers involved in all unconfirmed events', :all_speakers_in_unconfirmed_events],
      ['All speakers involved in all scheduled events', :all_speakers_in_scheduled_events]
    ]
  end

  def send_mail
    @mail_template = @conference.mail_templates.find(params[:id])
    send_filter = params[:send_filter]

    if Rails.env.production?
      @mail_template.send_async(send_filter)
      redirect_to(@mail_template, notice: 'Mail deliveries queued.')
    else
      @mail_template.send_sync(send_filter)
      redirect_to(@mail_template, notice: 'Mails delivered.')
    end
  end

  def index
    result = search @conference.mail_templates, params
    @mail_templates = result.paginate page: page_param
  end

  def update
    @mail_template = @conference.mail_templates.find(params[:id])

    respond_to do |format|
      if @mail_template.update_attributes(mail_template_params)
        format.html { redirect_to(@mail_template, notice: 'Mail template was successfully updated.') }
        format.xml  { head :ok }
        format.js   { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    t = MailTemplate.new(mail_template_params)
    @conference.mail_templates << t
    redirect_to(mail_templates_path, notice: 'Transport need was successfully added.')
  end

  def destroy
    @conference.mail_templates.find(params[:id]).destroy
    redirect_to(mail_templates_path, notice: 'Mail template was successfully destroyed.')
  end

  private

  def search(mail_templates, params)
    if params.key?(:term) and not params[:term].empty?
      term = params[:term]
      sort = begin
               params[:q][:s]
             rescue
               nil
             end
      @search = mail_templates.ransack(name_cont: term,
                                       subject_cont: term,
                                       content_cont: term,
                                       m: 'or',
                                       s: sort)
    else
      @search = mail_templates.ransack(params[:q])
    end

    @search.result(distinct: true)
  end

  def mail_template_params
    params.require(:mail_template).permit(:name, :subject, :content)
  end
end

app/views/mail_templates/_form.html.haml
%p
  The following place holders may be used in the
  %code content
  section of each template.
  %ul
    %li #first_name
    %li #last_name
    %li #public_name

= simple_form_for @mail_template do |f|
  %fieldset.inputs
    = f.input :name
    = f.input :subject, input_html: { size: 100 }
    = f.input :content, as: :text, input_html: { rows: 20 }
  .actions
    = f.button :submit, class: 'primary'

app/views/mail_templates/_send_form.html.haml
%h2 Send mail
%p
  Use this mail template to send a mail to all people involved in
  the events of this conference.

= simple_form_for @mail_template, url: send_mail_mail_template_path, html: { method: :put } do |f|
  .actions
    = select_tag "send_filter", options_for_select(@send_filter_options), style: "width:400px"
    = f.button :submit, "Send", class: 'danger'

app/views/mail_templates/_table.html.haml
%table.zebra-stripe
  %thead
    %tr
    - if @search
      %th= sort_link @search, :name, 'Name', term: params[:term]
      %th= sort_link @search, :subject, 'Subject', term: params[:term]
      %th= sort_link @search, :content, 'Content', term: params[:term]
      %th= sort_link @search, :created_at, term: params[:term]
    - else
      %th Name
      %th Subject
      %th Content
      %th Created at
    %th.last
  %tbody
    - collection.each do |t|
      %tr
        %td= link_to t.name, t
        %td= t.subject
        %td= t.content.truncate(100)
        %td= t.created_at
        %td.buttons
          = action_button "small", 'Show', t
          - if policy(@conference).orga?
            = action_button "small", 'Edit', edit_mail_template_path(t)
            = action_button "small danger", 'Destroy', t, data: { confirm: 'Are you sure?' }, method: :delete

app/views/mail_templates/edit.html.haml
%section
  .page-header
    %h1 Edit Mail template
  .row
    .span16
      = render 'form'

app/views/mail_templates/index.html.haml
%section
  .page-header
    .pull-right
      - if policy(@conference).orga?
        = action_button "primary", "Add mail template", new_mail_template_path, hint: "Add a new mail template."
    %h1 List of mail templates
  = render 'shared/search_and_table', collection: @mail_templates

app/views/mail_templates/new.html.haml
= block do
  = content do
    %h2 New mail template
    = inner do
      = render 'form'

app/views/mail_templates/show.html.haml
%section
  .page-header
    .pull-right
      - if policy(@conference).orga?
        = action_button "primary", "Edit mail template", edit_mail_template_path(@mail_template), hint: "Edit this mail template."
    %h1 Mail template '#{@mail_template.name}'
    %b Subject: #{@mail_template.subject}
    %pre= @mail_template.content
    %section
      .row
        .span16
          =render 'send_form'