config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'auth/registrations',
    sessions: 'auth/sessions'
  }

  scope '(:locale)' do

    get '/conferences/new' => 'conferences#new', as: 'new_conference'
    post '/conferences' => 'conferences#create', as: 'create_conference'
    get '/conferences' => 'conferences#index', as: 'conference_index'
    delete '/conferences' => 'conferences#destroy'

    get '/conferences/past' => 'home#past', as: 'past_conferences'

    get '/conference_users' => 'conference_users#index', as: 'conference_users'
    get '/admin_users' => 'conference_users#admins', as: 'admin_users'
    delete '/conference_users' => 'conference_users#destroy'

    get '/profile' => 'crew_profiles#edit', as: 'edit_crew_profile'
    patch '/profile' => 'crew_profiles#update', as: 'update_crew_profile'

    get '/user/:person_id/edit' => 'users#edit', as: 'edit_crew_user'
    patch '/user/:person_id' => 'users#update', as: 'crew_user'
    post '/user/:person_id' => 'users#create'

    scope path: '/:conference_acronym' do
      namespace :public do
        get '/schedule' => 'schedule#index', as: 'schedule_index'
        get '/schedule/style' => 'schedule#style', as: 'schedule_style'
        get '/schedule/:day' => 'schedule#day', as: 'schedule'
        get '/events' => 'schedule#events', as: 'events'
        get '/timeline' => 'schedule#timeline', as: 'timeline'
        get '/booklet' => 'schedule#booklet', as: 'booklet'
        get '/events/:id' => 'schedule#event', as: 'event'
        get '/speakers' => 'schedule#speakers', as: 'speakers'
        get '/speakers/:id' => 'schedule#speaker', as: 'speaker'
        get '/qrcode' => 'schedule#qrcode', as: 'qrcode'
        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do
        resource :user, except: %i(new create)
        resource :person do
          member do
            get :export
            post :import
          end
          resource :availability
        end
        get '/events/:id/confirm/:token' => 'events#confirm', as: 'event_confirm_by_token'
        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end
        root to: 'welcome#show'
      end # namespace :cfp

      get '/recent_changes' => 'recent_changes#index', as: 'recent_changes'
      post '/schedule.pdf' => 'schedule#custom_pdf', as: 'schedule_custom_pdf', defaults: { format: :pdf }
      get '/schedule' => 'schedule#index', as: 'schedule'
      get '/schedule/update_track' => 'schedule#update_track', as: 'schedule_update_track'
      put '/schedule/update_event' => 'schedule#update_event', as: 'schedule_update_event'
      get '/schedule/new_pdf' => 'schedule#new_pdf', as: 'new_schedule_pdf'
      get '/schedule/html_exports' => 'schedule#html_exports'
      post '/schedule/create_static_export' => 'schedule#create_static_export'
      get '/schedule/download_static_export' => 'schedule#download_static_export'

      get '/statistics/events_by_state' => 'statistics#events_by_state', as: 'events_by_state_statistics'
      get '/statistics/language_breakdown' => 'statistics#language_breakdown', as: 'language_breakdown_statistics'
      get '/statistics/gender_breakdown' => 'statistics#gender_breakdown', as: 'gender_breakdown_statistics'

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
	get :edit_classifiers
        get :edit_ticket_server
        get :edit_notifications
        post :send_notification
      end
      get '/conferences/default_notifications' => 'conferences#default_notifications', as: 'conferences_default_notifications'

      resource :call_for_participation

      resources :people do
        resource :user
        resource :availability, except: %i(create show)
        resources :expenses
        resources :transport_needs
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
        member do
          put :attend
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
          get :export_accepted
          get :export_confirmed
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
          post :custom_notification
        end
        resource :event_rating
        resources :event_feedbacks
      end

      get '/reports' => 'reports#index', as: 'reports'
      get '/reports/on_people/:id' => 'reports#show_people', as: 'report_on_people'
      get '/reports/on_events/:id' => 'reports#show_events', as: 'report_on_events'
      get '/reports/on_statistics/:id' => 'reports#show_statistics', as: 'report_on_statistics'
      get '/reports/on_transport_needs/:id' => 'reports#show_transport_needs', as: 'report_on_transport_needs'

      post '/tickets/:id/person' => 'tickets#create_person', as: 'create_person_ticket'
      post '/tickets/:id/event' => 'tickets#create_event', as: 'create_event_ticket'

      resources :mail_templates do
        member do
          put :send_mail
        end
      end
    end # scope path: "/:conference_acronym"
    get '/:conference_acronym' => 'conferences#show', as: 'conference_crew'
  end # scope "(:locale)" do

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @conferences = Conference.future.includes(:call_for_participation).paginate(page: page_param)
  end

  def past
    @conferences = Conference.past.includes(:call_for_participation).paginate(page: page_param)
    render 'index'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_table.html.haml
%table.zebra-striped
  %thead
    %th.first
    %th= t('activerecord.attributes.day.start_date')
    %th= t('activerecord.attributes.conference.title')
    %th= t(:actions)
  %tbody
    - collection.each do |conference|
      %tr
        %td
          - if conference.logo.present?
            = image_box conference&.logo, :small
        %td
          = l(conference.days.first.start_date.to_date)
          \-
          = l(conference.days.last.end_date.to_date)
        %td= conference.title
        %td
          - if show_cfp?(current_user, conference)
            = action_button 'small primary', t('participate'), cfp_person_path(conference_acronym: conference.acronym)
          - elsif conference&.call_for_participation&.welcome_text.present?
            = action_button 'small primary', t('activerecord.models.call_for_participation'), cfp_root_path(conference_acronym: conference.acronym)

          - if conference.schedule_public?
            = action_button 'small primary', t('schedule'), public_schedule_index_path(conference_acronym: conference.acronym)
          - if policy(conference).read?
            = action_button 'small secondary', t('show'), conference_path(conference_acronym: conference.acronym)

app/views/home/index.html.haml
- content_for :title do
  = link_to 'frab - home', root_url, class: 'brand'

%section
  .page-header
    .pull-right
      - if policy(Conference).new?
        = action_button "primary", "Add conference", new_conference_path, hint: "Add a new conference"
      - if policy(Conference).orga?
        = action_button "primary", "Manage conferences", conferences_path, hint: "Manage all conferences"
        = action_button "secondary", "Search", conferences_path, hint: "Seach conferences"
    %h1 List of conferences

  %ul.tabs
    %li{class: active_class?(root_path)}= link_to "Current Conferences", root_path
    %li{class: active_class?(past_conferences_path)}= link_to "Past Conferences", past_conferences_path

  - if Conference.all.empty? |
    .row
      .span16
        .blank-slate{style: 'padding-bottom: 33%'}
          %p
            There is not a single conference yet.

  - elsif @conferences.empty?
    .row
      .span16
        .blank-slate{style: 'padding-bottom: 33%'}
          %p
            There is no current conference with a call for participation. Maybe you need to log in?

  - else
    = render 'table', collection: @conferences
    = actions_bar do
      = will_paginate @conferences

  %hr

  - content_for :footer do
    .span16
      / :markdown
      /   [frab](http://frab.github.io/frab/) is a conference planning and management system. It helps to collect submissions, manage talks and speakers and create a schedule.

      /   The [users manual](https://github.com/frab/frab/wiki/Manual) is maintained in the [wiki](https://github.com/frab/frab/wiki/).  The source code is hosted on [Github](https://github.com/frab/frab).