config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'auth/registrations',
    sessions: 'auth/sessions'
  }

  scope '(:locale)' do

    get '/conferences/new' => 'conferences#new', as: 'new_conference'
    post '/conferences' => 'conferences#create', as: 'create_conference'
    get '/conferences' => 'conferences#index', as: 'conference_index'
    delete '/conferences' => 'conferences#destroy'

    get '/conferences/past' => 'home#past', as: 'past_conferences'

    get '/conference_users' => 'conference_users#index', as: 'conference_users'
    get '/admin_users' => 'conference_users#admins', as: 'admin_users'
    delete '/conference_users' => 'conference_users#destroy'

    get '/profile' => 'crew_profiles#edit', as: 'edit_crew_profile'
    patch '/profile' => 'crew_profiles#update', as: 'update_crew_profile'

    get '/user/:person_id/edit' => 'users#edit', as: 'edit_crew_user'
    patch '/user/:person_id' => 'users#update', as: 'crew_user'
    post '/user/:person_id' => 'users#create'

    scope path: '/:conference_acronym' do
      namespace :public do
        get '/schedule' => 'schedule#index', as: 'schedule_index'
        get '/schedule/style' => 'schedule#style', as: 'schedule_style'
        get '/schedule/:day' => 'schedule#day', as: 'schedule'
        get '/events' => 'schedule#events', as: 'events'
        get '/timeline' => 'schedule#timeline', as: 'timeline'
        get '/booklet' => 'schedule#booklet', as: 'booklet'
        get '/events/:id' => 'schedule#event', as: 'event'
        get '/speakers' => 'schedule#speakers', as: 'speakers'
        get '/speakers/:id' => 'schedule#speaker', as: 'speaker'
        get '/qrcode' => 'schedule#qrcode', as: 'qrcode'
        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do
        resource :user, except: %i(new create)
        resource :person do
          member do
            get :export
            post :import
          end
          resource :availability
        end
        get '/events/:id/confirm/:token' => 'events#confirm', as: 'event_confirm_by_token'
        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end
        root to: 'welcome#show'
      end # namespace :cfp

      get '/recent_changes' => 'recent_changes#index', as: 'recent_changes'
      post '/schedule.pdf' => 'schedule#custom_pdf', as: 'schedule_custom_pdf', defaults: { format: :pdf }
      get '/schedule' => 'schedule#index', as: 'schedule'
      get '/schedule/update_track' => 'schedule#update_track', as: 'schedule_update_track'
      put '/schedule/update_event' => 'schedule#update_event', as: 'schedule_update_event'
      get '/schedule/new_pdf' => 'schedule#new_pdf', as: 'new_schedule_pdf'
      get '/schedule/html_exports' => 'schedule#html_exports'
      post '/schedule/create_static_export' => 'schedule#create_static_export'
      get '/schedule/download_static_export' => 'schedule#download_static_export'

      get '/statistics/events_by_state' => 'statistics#events_by_state', as: 'events_by_state_statistics'
      get '/statistics/language_breakdown' => 'statistics#language_breakdown', as: 'language_breakdown_statistics'
      get '/statistics/gender_breakdown' => 'statistics#gender_breakdown', as: 'gender_breakdown_statistics'

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
	get :edit_classifiers
        get :edit_ticket_server
        get :edit_notifications
        post :send_notification
      end
      get '/conferences/default_notifications' => 'conferences#default_notifications', as: 'conferences_default_notifications'

      resource :call_for_participation

      resources :people do
        resource :user
        resource :availability, except: %i(create show)
        resources :expenses
        resources :transport_needs
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
        member do
          put :attend
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
          get :export_accepted
          get :export_confirmed
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
          post :custom_notification
        end
        resource :event_rating
        resources :event_feedbacks
      end

      get '/reports' => 'reports#index', as: 'reports'
      get '/reports/on_people/:id' => 'reports#show_people', as: 'report_on_people'
      get '/reports/on_events/:id' => 'reports#show_events', as: 'report_on_events'
      get '/reports/on_statistics/:id' => 'reports#show_statistics', as: 'report_on_statistics'
      get '/reports/on_transport_needs/:id' => 'reports#show_transport_needs', as: 'report_on_transport_needs'

      post '/tickets/:id/person' => 'tickets#create_person', as: 'create_person_ticket'
      post '/tickets/:id/event' => 'tickets#create_event', as: 'create_event_ticket'

      resources :mail_templates do
        member do
          put :send_mail
        end
      end
    end # scope path: "/:conference_acronym"
    get '/:conference_acronym' => 'conferences#show', as: 'conference_crew'
  end # scope "(:locale)" do

  root to: 'home#index'
end

app/controllers/reports_controller.rb
class ReportsController < BaseConferenceController
  before_action :orga_only!

  def index
    respond_to do |format|
      format.html
    end
  end

  def show_events
    @report_type = params[:id]
    @events = []
    @search_count = 0
    @extra_fields = []

    conference_events = @conference.events
    if params[:term]
      conference_events = @conference.events.ransack(params[:term]).result
    end

    case @report_type
    when 'lectures_with_speaker'
      r = conference_events.with_speaker.where(event_type: :lecture)
    when 'lectures_not_confirmed'
      r = conference_events.with_speaker.where(event_type: :lecture, state: [:new, :review])
    when 'events_not_public'
      r = conference_events.where(public: false)
    when 'events_that_are_workshops'
      r = conference_events.where(Event.arel_table[:event_type].eq(:workshop))
    when 'event_timeslot_deviation'
      r = conference_events.where(event_type: :lecture).where('time_slots != ?', @conference.default_timeslots)
    when 'events_that_are_no_lectures'
      r = conference_events.where(Event.arel_table[:event_type].not_eq(:lecture).and(Event.arel_table[:event_type].not_eq(:workshop)))
    when 'events_without_speaker'
      r = conference_events.without_speaker
    when 'events_with_more_than_one_speaker'
      r = conference_events.with_more_than_one_speaker
    when 'events_without_abstract'
      r = conference_events.where(Event.arel_table[:abstract].eq(''))
    when 'unconfirmed_events'
      r = conference_events.where(event_type: :lecture, state: :unconfirmed)
    when 'events_with_a_note'
      r = conference_events.where(Event.arel_table[:note].not_eq('').or(Event.arel_table[:submission_note].not_eq('')))
    when 'events_with_unusual_state_speakers'
      r = conference_events.joins(:event_people).where(event_people: { role_state: [:canceled, :declined, :idea, :offer, :unclear], event_role: [:moderator, :speaker] })
    when 'do_not_record_events'
      r = conference_events.where(do_not_record: true)
    when 'events_with_tech_rider'
      r = conference_events
        .scheduled
        .where(Event.arel_table[:tech_rider].not_eq(''))
      @extra_fields << :tech_rider
    end

    unless r.nil? or r.empty?
      @search = r.search(params[:q])
      @search_count = r.count
      @events = @search.result.paginate page: page_param
    end
    respond_to do |format|
      format.html { render :show }
    end
  end

  def show_people
    @report_type = params[:id]
    @people = []
    @search_count = 0
    @extra_fields = []

    conference_people = Person
    conference_people = Person.ransack(params[:term]).result if params[:term]

    case @report_type
    when 'expected_speakers'
      r = Person.joins(events: :conference)
        .where('conferences.id': @conference.id)
        .where('event_people.event_role': EventPerson::SPEAKER)
        .where('event_people.role_state': 'confirmed')
        .where('events.public': true)
        .where('events.start_time > ?', Time.now)
        .where('events.start_time < ?', Time.now.since(4.hours))
        .where('events.state': %w(unconfirmed confirmed scheduled))
        .distinct
    when 'people_speaking_at'
      r = conference_people.speaking_at(@conference)
    when 'people_with_a_note'
      r = conference_people.involved_in(@conference).where(Person.arel_table[:note].not_eq(''))
    when 'people_with_more_than_one'
      r = conference_people.involved_in(@conference).where('event_people.event_role' => ['submitter']).group('event_people.person_id').having('count(*) > 1')
    when 'people_with_non_reimbursed_expenses'
      r = conference_people.involved_in(@conference).joins(:expenses).where('expenses.value > 0 AND expenses.reimbursed = ? AND expenses.conference_id = ?', false, @conference.id)
      @total_sum = 0
      r.each do |p|
        @total_sum += p.sum_of_expenses(@conference, false)
      end

      @extra_fields << :expenses
    when 'non_attending_speakers'
      r = Person.joins(events: :conference)
        .where('conferences.id': @conference.id)
        .where('event_people.event_role': 'speaker')
        .where("event_people.role_state != 'attending'")
        .where('events.public': true)
        .where('events.start_time > ?', Time.now)
        .where('events.start_time < ?', Time.now.since(2.hours))
        .where('events.state': %w(accepting unconfirmed confirmed scheduled))
        .distinct
    when 'speakers_without_availabilities'
      r = Person.joins(events: :conference)
        .includes(:availabilities)
        .where('conferences.id': @conference.id)
        .where('event_people.event_role': EventPerson::SPEAKER)
        .where('event_people.role_state': [ 'confirmed', 'scheduled' ])
        .where(availabilities: { person_id: nil })
    end

    unless r.nil? or r.empty?
      @search = r.search(params[:q])
      @search_count = r.length
      @people = @search.result.paginate page: page_param
    end
    respond_to do |format|
      format.html { render :show }
    end
  end

  def show_statistics
    @report_type = params[:id]
    @search_count = 0

    case @report_type
    when 'confirmed_events_by_track'
      @data = []
      row = []
      @labels = @conference.tracks.collect(&:name)
      @labels.each { |track|
        row << @conference.events.confirmed.joins(:track).where(tracks: { name: track }).count
      }
      @data << row
      @search_count = row.inject(:+)

    when 'events_by_track'
      @data = []
      row = []
      @labels = @conference.tracks.collect(&:name)
      @labels.each { |track|
        row << @conference.events.candidates.joins(:track).where(tracks: { name: track }).count
      }
      @data << row
      @search_count = row.inject(:+)

    when 'event_timeslot_sum'
      @data = []
      row = []
      @labels = %w(LecturesCommited LecturesConfirmed LecturesUnconfirmed Lectures Workshops)
      events = @conference.events.where(event_type: :lecture, state: [:accepting, :confirmed, :unconfirmed, :scheduled])
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture, state: [:confirmed, :scheduled])
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture, state: [:acepting, :unconfirmed])
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture)
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :workshops)
      row << @conference.event_duration_sum(events)
      @data << row
      @search_count = nil

    when 'people_speaking_by_day'
      @data = []
      row = []
      @labels = %w(Day FullName PublicName Email Event Role State) # TODO translate

      @conference.days.each do |day|
        @conference.events.confirmed.no_conflicts.is_public.scheduled_on(day).order(:start_time).each do |event|
          event.event_people.presenter.each do |event_person|
            person = event_person.person
            row = [l(day.date), person.full_name, person.public_name, person.email, event.title, event_person.event_role, event_person.role_state]
            @data << row
          end
        end
      end

      @search_count = nil
    end

    respond_to do |format|
      format.html { render :show }
    end
  end

  def show_transport_needs
    @search = @conference.transport_needs.search(params[:q])
    @transport_needs = @search.result
    @report_type = params[:id]

    render :show
  end
end

app/views/reports/_events_table.html.haml
%table.zebra-stripe
  %thead
    %tr
      %th.first
      - if @search
        %th= sort_link @search, :title, "Title", term: params[:term]
        %th= sort_link @search, :track_name, "Track", term: params[:term]
        %th= sort_link @search, :event_type, term: params[:term]
        %th= sort_link @search, :state, "State", term: params[:term]
        %th= sort_link @search, :start_time, term: params[:term]
        - if @extra_fields.include?(:tech_rider)
          %th Tech rider
      - else
        %th Title
        %th Track
        %th Event type
        %th State
        %th Start time
        - if @extra_fields.include?(:tech_rider)
          %th Tech rider
      %th
  %tbody
    - events.each do |event|
      %tr
        %td= link_to (image_box event.logo, :small), event
        %td
          = link_to event.title, event
          %p.small
            = by_speakers(event)
        %td= event.track.try(:name)
        %td= event.event_type
        %td= event.state
        %td= event.start_time ? l(event.start_time) : ""
        - if @extra_fields.include?(:tech_rider)
          %td= event.tech_rider
        %td.buttons
          = action_button "small", 'Show', event
          - if policy(@conference).manage?
            = action_button "small", 'Edit', edit_event_path(event)
            = action_button "small danger", 'Destroy', event, data: { confirm: 'Are you sure?' }, method: :delete

app/views/reports/_people_table.html.haml
%table.zebra-stripe
  %thead
    %tr
      %th.first
      - if @search
        %th= sort_link @search, :full_name, term: params[:term]
        %th= sort_link @search, :public_name, term: params[:term]
        %th= sort_link @search, :email, term: params[:term]
        %th Events in
        %th= sort_link @search, :created_at, term: params[:term]
        - if @extra_fields.include?(:expenses)
          %th Non-reimbursed expenses
      - else
        %th Full name
        %th Public name
        %th Email
        %th Events in
        %th Created at
      %th.last
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to (image_box person.avatar, :small), person
        %td= link_to person.full_name, person
        %td
          -unless person.public_name.nil?
            = link_to person.public_name, person
        %td= link_to person.email, person
        %td= person.events_in(@conference).map{|e| link_to e.title, e}.join(', ').html_safe
        %td= l(person.created_at.to_date)
        - if @extra_fields.include?(:expenses)
          %th= to_currency person.sum_of_expenses(@conference, false)
        %td.buttons
          = action_button "small", 'Show', person
          - if policy(@conference).manage?
            = action_button "small", 'Edit', edit_person_path(person)
            = action_button "small danger", 'Destroy', person, data: { confirm: 'Are you sure?' }, method: :delete

    - if @extra_fields.include?(:expenses)
      %tr
        %td{ colspan: 5 }
        %td
          %b Total
        %td{ colspan: 2 }
          %b= to_currency @total_sum

app/views/reports/_report_menu.html.haml
%p Query Events
%ul
  %li= link_to "lectures with speaker", report_on_events_path('lectures_with_speaker')
  %li= link_to "lectures that are new or review", report_on_events_path('lectures_not_confirmed')
  %li= link_to "events that are unconfirmed", report_on_events_path("unconfirmed_events")
  %li= link_to "events that are not public", report_on_events_path("events_not_public")
  %li= link_to "list of all workshops", report_on_events_path('events_that_are_workshops')
  %li= link_to "events that are neither lectures nor workshops", report_on_events_path('events_that_are_no_lectures')
  %li= link_to "events with a note", report_on_events_path('events_with_a_note')
  %li= link_to "events without speaker", report_on_events_path('events_without_speaker')
  %li= link_to "events without abstract", report_on_events_path('events_without_abstract')
  %li= link_to "events with speakers in a problematic state", report_on_events_path("events_with_unusual_state_speakers")
  %li= link_to "events with 'do not record' flag set", report_on_events_path("do_not_record_events")
  %li= link_to "events with more than one speaker", report_on_events_path("events_with_more_than_one_speaker")
  %li= link_to "list all lectures with non default timeslots", report_on_events_path('event_timeslot_deviation')
  %li= link_to "list all scheduled events with tech riders", report_on_events_path('events_with_tech_rider')
%p Query Speakers
%ul
  %li= link_to "missing speakers for the next 4 hours", report_on_people_path("expected_speakers")
  %li= link_to "confirmed people speaking at conference", report_on_people_path("people_speaking_at")
  %li= link_to "people with a note in their submission", report_on_people_path("people_with_a_note")
  %li= link_to "people with more than one submission", report_on_people_path("people_with_more_than_one")
  - if @conference.expenses_enabled?
    %li= link_to "people with non-reimbursed expenses", report_on_people_path("people_with_non_reimbursed_expenses")
  %li= link_to "non-attending speakers for the next 2 hours", report_on_people_path("non_attending_speakers")
  %li= link_to "speakers without availabilities", report_on_people_path("speakers_without_availabilities")
%p Statistics
%ul
  %li= link_to "used timeslots (hours)", report_on_statistics_path("event_timeslot_sum")
  %li= link_to "confirmed event numbers by track", report_on_statistics_path("confirmed_events_by_track")
  %li= link_to "event numbers by track", report_on_statistics_path("events_by_track")
  %li= link_to "confirmed speakers by day with attendance status", report_on_statistics_path("people_speaking_by_day")

- if @conference.transport_needs_enabled?
  %p Transport needs
  %ul
    %li= link_to "overview on transport needs", report_on_transport_needs_path("all")

app/views/reports/_statistics_table.html.haml
%table.zebra-stripe
  %thead
    %tr
    - @labels.each do |label|
      %th= label
  %tbody
    - @data.each do |row|
      %tr
      - row.each do |c|
        %td= c

app/views/reports/_transport_needs_table.html.haml
%table.zebra-stripe
  %thead
    %tr
      %th.first
      - if @search
        %th= sort_link @search, :name, :term => params[:term]
        %th= sort_link @search, :at, :term => params[:term]
        %th= sort_link @search, :transport_type, :term => params[:term]
        %th= sort_link @search, :seats, :term => params[:term]
        %th= sort_link @search, :booked, :term => params[:term]
        %th= sort_link @search, :note, :term => params[:term]
      - else
        %th Name
        %th When
        %th Type
        %th # of seats
        %th Booked
        %th Note
      %th.last
  %tbody
    - transport_needs.each do |tn|
      %tr
        %td= link_to (image_box tn.person.avatar, :small), tn.person
        %td= link_to tn.person.full_name, tn.person
        %td= tn.at.to_formatted_s(:long)
        %td= tn.transport_type
        %td= tn.seats
        %td= t_boolean(tn.booked)
        %td= tn.note

app/views/reports/index.html.haml
%section
  .page-header
    %h1 Available Reports
  = render 'report_menu'

app/views/reports/show.html.haml
%section
  .page-header
    %h1 Available Reports
  = render 'report_menu'
  %h2 Results
  - if @people or @events
    = render 'shared/simple_search', path: request.path
  - unless @search_count.nil?
    Found
    = @search_count
    results.
  - if not @people.nil? and not @people.empty?
    .row
      .span16
        - if @people.all.empty?
          %p Sorry, but your search yielded no results.
        - else
          = render 'people_table', people: @people
          = actions_bar do
            = will_paginate @people
  - if not @events.nil? and not @events.empty?
    .row
      .span16
        - if @events.all.empty?
          %p Sorry, but your search yielded no results.
        - else
          = render 'events_table', events: @events
          = actions_bar do
            = will_paginate @events
  - if not @data.nil? and not @data.empty?
    .row
      .span16
        = render 'statistics_table', data: @data
  - if not @transport_needs.nil? and not @transport_needs.empty?
    .row
      .span16
        = render 'transport_needs_table', transport_needs: @transport_needs